### ISSUE TITLE
TMT

### ISSUE THREAD

**Issue by ohovey5** [tbaccata/amica#1]
Is this software compatible with Fragpipe TMT experiments?

**Comment by tbaccata** [comment]
Thanks for showing interest in amica!
So far, amica has only been tested with FragPipe's LFQ workflow. By default, amica can parse FragPipe's `combined_protein.tsv` output. Looking at the TMT example in FragPipe's doc (https://fragpipe.nesvilab.org/docs/tutorial_tmt-2plexes.html#analyze-the-whole-proteome-samples),  the TMT workflow also outputs a `combined_protein.tsv` file. Testing this with the example TMT `combined_protein.tsv` file, amica is able to read in and analyze this output.

Best,
Sebastian
