### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Maithy15** [tbaccata/amica#10]
Hi I am trying to analyse my data from MQ and getting the following error "error in limma Error in names(x) <- value: 'names' attribute [2] must be the same length as the vector [0]" could you please tell me what the problem could be?

Also, the example files are in .csv format and Amica asks for tsv files. Is it possible to change that?

**Comment by tbaccata** [comment]
Hey!

Thanks for reporting, so far I haven't encountered this error message. 
Do you mind sharing a minimal example of your files for me to reproduce the error?

Regarding the example files, they are tab-separated, but have an unfortunate file extension.
I will have a look at that.

Best,
Sebastian

**Comment by Maithy15** [comment]
Hi,

Please find the example protein groups file as well as the Amica expt. and grouping files.

Thanks
Maithy

[proteinGroups_amica.txt](https://github.com/tbaccata/amica/files/8442819/proteinGroups_amica.txt)
[amica_Expt.txt](https://github.com/tbaccata/amica/files/8442820/amica_Expt.txt)
[amica_Groups.txt](https://github.com/tbaccata/amica/files/8442821/amica_Groups.txt)

**Comment by tbaccata** [comment]
Hi Maithy,


the groups `CQStr` and `CQUnStr` in `amica_Groups.txt` are not defined in the experimental design `amica_Expt.txt`.
This should be changed to the defined groups `CQSTR` and `CQUnSTR`, then it works.

There should be an informative error message in such cases, 
that for whatever reason is not displayed, I'll look into this. 


Best,
Sebastian

**Comment by Maithy15** [comment]
ahh there is a mistake in the caps and small letter

Thanks for the help
Maithy

**Comment by tbaccata** [comment]
line 232/233 in R/server/upload.R should be changed from

```
if (!is.null(reacValues$expDesign) &
          length(grep(elem, reacValues$expDesign)) < 1) 
```

to  
```
if (!is.null(reacValues$expDesign$groups) &
          length(grep(elem, reacValues$expDesign)) < 1) 
```

and the user gets an appropriate error message.

Best,
Sebastian
