### ISSUE TITLE
After uploading files, nothing happened in the web and error message in R 

### ISSUE THREAD

**Issue by jounghyun-um** [tbaccata/amica#13]
Hi, I would like to use Amica for my proteomic data. 
However, when I uploaded my files, the screen changed to grey and does not move from there. 
So, I tried to run Amica from R and there was an error message like below.

Warning: Error in $<-.data.frame: replacement has 0 rows, data has 48

Could you tell me what I did wrong? 

Kind regards, 
J.

**Comment by tbaccata** [comment]
Hello!

Sorry for answering a bit late!
Your exp. design and contrast matrix are comma-separated, they should be tab-separated.

In addition, the groups defined in the experimental design should have no whitespace in them.
If you use these files, it should work.

[contrasts.txt](https://github.com/tbaccata/amica/files/8584021/contrasts.txt)
[design.txt](https://github.com/tbaccata/amica/files/8584022/design.txt)


Best,
Sebastian
