### ISSUE TITLE
Manual submission of protein list for highlighting in volcano plot

### ISSUE THREAD

**Issue by hollenstein** [tbaccata/amica#18]
Hi Sebastian,

I was asked by a user of Amica if it would be possible to add an additional protein selection option to the Volcano plot in the "Differential abundance" tab? Specifically, it would be useful to have the option to manually submit a list of protein identifiers (Uniprot IDs, Gene names, ...), which are then highlighted and labeled in the volcano plot, similar to what is happening if you use the selection tool. Optimally, the highlighted dots would be plotted above the other points and highlighted with a different color.

Please let me know if it is possible to add this feature.

Best,
David

**Comment by tbaccata** [comment]
Hi David,

that would be a useful feature, I will take a look into this.
It might take a couple of weeks.

Best,
Sebastian

**Comment by tbaccata** [comment]
Hi David,

I've added this feature, from now on user's have the option to select multiple proteins in a dropdown menu.

Cheers,
Sebastian
