### ISSUE TITLE
Error processing DIA-NN data

### ISSUE THREAD

**Issue by stratei86** [tbaccata/amica#20]
Hi,

I managed to upload correctly data from DIA-NN but when I click on analyze the app crashes and the console prints the following error

Warning: Error in :: argument of length 0

Is there anything I'm missing?

Thanks
Lucio

**Comment by tbaccata** [comment]
Hello Lucio,

The issue happens during Analysis, Upload works fine.
It's difficult to assess where the error comes from, the DIA-NN parser does not have many options.

Could you please send me a the first couple of lines of your PG matrix, your exp. design file and your contrast matrix file?
sebastian.dididusch@univie.ac.at

Best,
Sebastian

**Comment by tbaccata** [comment]
> 

Sorry, wrong email:

sebastian.didusch@univie.ac.at
