### ISSUE TITLE
Maximum upload size exceeded

### ISSUE THREAD

**Issue by bolak92** [tbaccata/amica#23]
Hi,
I am trying to analyze MaxQuant data on local installation of amica. But when I upload the proteinGroups.txt file, a message appears stating that the maximum upload size exceeded, how can I solve this issue?
![image](https://github.com/tbaccata/amica/assets/49613273/b111ad81-0574-4b5e-a906-a27501e0c155)

Regards, 
Bola

**Comment by tbaccata** [comment]
Dear Bola,

the max. file size is set to 75MB on the server and in the code on github.
If you want to change it on your local version, you need to alter line 5 of the file server.R (https://github.com/tbaccata/amica/blob/master/amica/server.R):

`options(shiny.maxRequestSize = 75 * 1024 ^ 2)`

Here you can replace 75 with the number of MBs you'd need.

Best,
Sebastian
