### ISSUE TITLE
"X" prefix added to sample names upon uploading experimental design file

### ISSUE THREAD

**Issue by bolak92** [tbaccata/amica#24]
Hello,

I've encountered an issue where an "X" prefix gets added to sample names when I upload the experimental design file.

Below is a screenshot from the original .txt file, where the sample names don't have the "X" prefix: 
![image](https://github.com/tbaccata/amica/assets/49613273/97a8afda-34ff-4549-bcf0-66d901be4b5b)

However, when uploaded to the amica server, the "X" prefix appears:
![image](https://github.com/tbaccata/amica/assets/49613273/ffba0b97-9492-4333-9223-ba5072a9f1bc)

Is there any workaround for this issue? The prefix also gets carried over to the graphs, which is not ideal.

Thank you for your assistance!

**Comment by tbaccata** [comment]
Hey!

For the time being, this won't be changed. 
his is an annoying prefix when the 1st character is not a letter.
The only quick solution would be to rename all intensity and iBAQ sample names in your MQ output and experimental design.

Best,
Sebastian

**Comment by bolak92** [comment]
Thanks Sebastian, 
your prompt responses really help a lot.

Regards, 
Bola
