### ISSUE TITLE
`RawIntensity` values identical to `ImputedIntensity`

### ISSUE THREAD

**Issue by bolak92** [tbaccata/amica#28]
Hello,

During a recent data analysis, I observed that the `RawIntensity` values in the exported amica file are identical to the `ImputedIntensity` values. This occurred after a run with vsn normalization and no imputation.

Steps to Reproduce:

1. Conduct a run with vsn normalization.
2. Ensure no imputation is selected.
3. Export the amica file.
4. Inspect the values of `RawIntensity` and  `ImputedIntensity`.

I suspect this behavior might be a bug. Would you be able to provide clarification or confirm the issue?

Kind Regards, Bola

**Comment by bolak92** [comment]
I am suspecting that this happens around line 293 if file runAnalysis.R that the cols RawIntensity gets replaced by ImputedIntensity  in place.

**Comment by tbaccata** [comment]
Hey Bola,

I'm assuming you have MaxQuant output?
Using amica's provided example data, that contains MQ's summed intensities (= raw intensities), LFQ intensities and iBAQ intensities, I could not reproduce this behavior.

All intensities differ after the analysis step.
In line 293 amica's imputed intensities are getting updated after (potential) normalization.

Best,
Sebastian
