### ISSUE TITLE
Help understanding contrasts differential expression

### ISSUE THREAD

**Issue by Klorator** [tbaccata/amica#32]
Hi, 

I'm trying to cobble together a script performing differential expression with DEqMS and am getting different output from my script compared to using Amica. Why am I getting one output (one column of p-values) from my script but an output for every comparison from Amica?

I've followed [the vignette, point 2.2](https://www.bioconductor.org/packages/release/bioc/vignettes/DEqMS/inst/doc/DEqMS-package-vignette.html#deqms-analysis-using-maxquant-outputs-label-free-data), and the code runs. My question for now revolves around the contrast. I've used a character vector `cont <- c("A-B", "A-C", "B-C")` as seen in the `limma::makeContrasts` documentation. This later outputs one dataframe/column of p-values for everything. On the other hand, when my colleague uses Amica they get a dataframe for every comparison (in this case three).

Can you help me understand how Amica (and thereby limma/DEqMS) uses the contrasts and what the difference would be caused by in this case?

**Comment by tbaccata** [comment]
Hi!

Sorry for the late reply. 
The amica code just iterates through all contrasts from the contrast matrix, and append log2FCs and p-values to an output data.frame (see https://github.com/tbaccata/amica/blob/master/amica/R/utils.R#L127).

Best,
Sebastian
