### ISSUE TITLE
Wrong group labels in PCA caused by mismatch of sample order in the table and design

### ISSUE THREAD

**Issue by hollenstein** [tbaccata/amica#33]
Hi Sebastian,

we've noticed an issue with the groups in the PCA plot being wrongly labeled (and possible other plots but we didn't check all of them). The cause of the issue is when the order of samples in the design does not reflect the order of the samples in the table. I know that this violates the requirements of the design file as the info says:

_"The sample names in the samples column need to match the column names of the input file in the order of the input file."_

I still wanted to ask if you would be willing to allow a mismatch of sample order in the design and the table or not.

Best,
David

**Comment by tbaccata** [comment]
Hi David,

This will affect quite a lot of the downstream analysis and outputs.
It's written in the requirements, but a sanity check/alternative mapping would probably be a good idea.

Best,
Sebastian

**Comment by xeniorn** [comment]
Dear Sebastian,

looking at the code, it seems to me like it would be possible to avoid this requirement without changing any of the analysis and output code, by putting the columns in the correct order at input time, when constructing the ProteomicsData object, in "readInAmicaSumm" and equivalent functions, where you are anyhow iterating through all columns, and the function is already taking both design and data as input.

Does this make sense? Or are the input files used elsewhere directly?

Best,

J

**Comment by hollenstein** [comment]
Dear Sebastian,

Do you plan on implementing a fix, and if so, until when you think it will be done? I am just asking because if it takes too long I will fix the issue on our side, to prevent giving out faulty amica input files.

Best,
David

**Comment by tbaccata** [comment]
Hey David,

I will take care of it, the fix should be implemented by the beginning of next week.

Best,
Sebastian

**Comment by hollenstein** [comment]
Nice =)

Thank you very much!
