### ISSUE TITLE
Custom file uploading issue

### ISSUE THREAD

**Issue by rajeshksoni11** [tbaccata/amica#6]
HI,
I have t output from DIA-NN, would you able to help for correct formatting.

Protein.Group | Protein.Ids | Protein.Names | Genes | First.Protein.Description | 388 | 399 | 404 | 405 | 407 | 408
388 _Control
399_Control
404_Control
405_KO
407_KO
408_KO

Best,

**Comment by tbaccata** [comment]
Hello!

amica needs to find a common pattern for the relevant columns (e.g intensities), 
assuming that columns 388 to 408 correspond to your intensitity columns, you would need to rename them to include a common pattern (e.g add an `LFQIntensity` - prefix):

|  Protein.Group | Protein.Ids | Protein.Names | Genes | First.Protein.Description | LFQIntensity_Control_388 | LFQIntensity_Control_399 | LFQIntensity_Control_404 | LFQIntensity_KO_405 | LFQIntensity_KO_407 | LFQIntensity_KO_408 |
|  ------------- | -------------  | ------------- | -------------  |  -------------  | ------------- | ------------- | ------------- | ------------- |  ------------- | ------------- |

After adding this prefix to the column names of the data and saving this file as a tab-delimited txt file, you can create your tab-delimited exp. design and contrasts txt files, and a tab-delim. specification file, that maps relevant columns in your data to amicas format (see attache files). 
In your case, you need to select a protein id (this column needs to have unique entries), a gene name and the intensity prefix:

|  Variable | Pattern | 
|  ------------- | -------------  | 
| proteinId | Protein.Ids |
| geneName | Genes |
| intensityPrefix | LFQIntensity_ |

Hope that helps!

Best,
Sebastian

[contrasts.txt](https://github.com/tbaccata/amica/files/7745103/contrasts.txt)
[design.txt](https://github.com/tbaccata/amica/files/7745104/design.txt)
[specification.txt](https://github.com/tbaccata/amica/files/7745105/specification.txt)
